
name: small linting action

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md
      - resources/*
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - resources/*
      - .gitignore

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
  
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 $REPO_FOLDER --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 $REPO_FOLDER --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
